### ISSUE TITLE
Issue with class

### ISSUE THREAD

**Issue by jhubb-io** [anomalylabs/blocked_check-extension#1]
I'm getting the following on all pages and on php artisan clear-compiled

FatalErrorException in SuspensionSecurityCheckExtension.php line 24:
Class Anomaly\SuspensionSecurityCheckExtension\SuspensionSecurityCheckExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Anomaly\UsersModule\Security\SecurityCheckExtension::check)

**Comment by RyanThompson** [comment]
Checkout 1.0/master of the user module - youll pry need to reinstall after that (or fresh clone will do it).
